domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: https://gopimn.github.io/mandofighters/     # place folder name if the site is served in a subfolder
# remote_theme: pages-themes/modernist@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mandoade
theme: jekyll-theme-minimal
description: kill
